#ifndef _FLUOROPHORE_MODEL_TYPES_H_
#define _FLUOROPHORE_MODEL_TYPES_H_


typedef enum {
  GEOMETRY_VERTICES,
  UNIFORM_RANDOM_SURFACE_SAMPLE,
  UNIFORM_RANDOM_VOLUME_SAMPLE
} FluorophoreModelType;

typedef enum {
  RED_CHANNEL,
  GREEN_CHANNEL,
  BLUE_CHANNEL,
  ALL_CHANNELS
} FluorophoreChannelType;


#endif // _FLUOROPHORE_MODEL_TYPES_H_
