#ifndef _FLUOROPHORE_MODEL_CHANNELS_H_
#define _FLUOROPHORE_MODEL_CHANNELS_H_

typedef enum {
  RED_CHANNEL,
  GREEN_CHANNEL,
  BLUE_CHANNEL,
  ALL_CHANNELS
} FluorophoreChannelType;

#endif // _FLUOROPHORE_MODEL_CHANNELS_H_
